#I am a member of Amazon and Namecheap's affiliate networks and I may
# earn a commision on anything you get with those links
patreon: faraixyz
ko_fi: faraixyz

custom: 
    - "https://farai.xyz/support"
    - "https://www.buymeacoffee.com/faraixyz"
    - "https://paypal.me/fgandiya"
    - "https://shareasale.com/r.cfm?b=467188&u=2110247&m=46483&urllink=namecheap%2Ecom&afftrack=farai%2Exyz"
